### PR TITLE
Tophat speed

### PR DESCRIPTION
**Pull request by romangrothausmann**
ITK-CLI to mimic the SITK-CLI [`tophat-speed.r`](https://github.com/romangrothausmann/SITK-CLIs/blob/4fccdf0450a1b6bcc3ca661e9797f95172c03f2f/tophat-speed.r) but to allow streaming due to the high memory needs of the R-version, see https://github.com/romangrothausmann/SITK-CLIs/pull/3.

`WhiteTopHatImageFilter` needs more than 750GB of mem. for a dataset of 3k^3 voxel while with streaming of 100 chunks the max. mem. needed is ~15GB.
Using `DiscreteGaussianImageFilter` (capable of streaming) instead of `SmoothingRecursiveGaussianImageFilter` (cannot stream) leads to some differences though: https://github.com/romangrothausmann/ITK-CLIs/commit/286450806478807d527fdf5d8d286253ee554338

### CODE REVIEW

**Comment by romangrothausmann** [comment]
@richardbeare Using this `tophat-speed` instead of your `tophat-speed.r` on the reduced dataset concerning https://github.com/InsightSoftwareConsortium/ITK/issues/6352 I am now hitting https://github.com/InsightSoftwareConsortium/ITK/issues/715, i.e. 
```
itk::ExceptionObject (0x1b5bf80)
Location: "unknown" 
File: /opt/itk/include/ITK-5.0/itkFastMarchingImageFilter.hxx
Line: 496
Description: Discriminant of quadratic equation is negative
```
Any idea what could be the reason for that?

**Comment by richardbeare** [comment]
No particular insight, I'm afraid. Things I'd check - are the target points on reasonably high values of the speed function, and are there definitely no constrictions where the only path is a single voxel corner connected one? Confirm that the speed image range is 0-1.

PS - making progress with the way-point issue.

**Comment by romangrothausmann** [comment]
It is possible to avoid the `Discriminant of quadratic equation is negative`-error by first down-sampling to a resolution of 450nm and then applying this `tophat-speed` ITK-CLI ([17-297e_1_s02 on branch SRV@450](https://gitlab.com/romangrothausmann/17-297e_1_s02/commit/8e15a89a5c5eda703409491f70c726e492542188)). The resulting path deverges from that from `tophat-speed.r` over a short distance, which could be due to either the other precision (https://github.com/romangrothausmann/ITK-CLIs/pull/5/commits/2b69683437f16c431889ffcc7b332c21b08f4deb) or the change to `DiscreteGaussianImageFilter` (https://github.com/romangrothausmann/ITK-CLIs/pull/5/commits/286450806478807d527fdf5d8d286253ee554338).
Merging, as it basically works as expected.

**Comment by romangrothausmann** [comment]
Just noticed that the output is not exactly zero where the input is. 
@richardbeare do you have an idea what could be different concerning the processing in regard to your R-version?

**Comment by romangrothausmann** [comment]
Seems I translated `input > 0` wrongly: https://github.com/romangrothausmann/ITK-CLIs/commit/9e31f6eef20bbe30aa93c9e35169675adac2ea34

**Comment by romangrothausmann** [comment]
Still the output of the R-Version and the ITK-CLI differ, now even more even if `SmoothingRecursiveGaussianImageFilter` is still used:
before (https://github.com/romangrothausmann/ITK-CLIs/pull/5/commits/2b69683437f16c431889ffcc7b332c21b08f4deb):
```
Min: 0 Max: 5.96046e-08 Mean: 8.42981e-11 Std: 1.34393e-09 Variance: 1.80615e-18 Sum: 0.000506232
```

now:
```
Min: -2.5034e-05 Max: 0.866582 Mean: 0.0162504 Std: 0.0396978 Variance: 0.00157592 Sum: 97587.7
```

@richardbeare any idea if there is some other inconsistency?

**Comment by richardbeare** [comment]
I'm doing a final masking step in the R version, however I think it is redundant. Is the difference the same with and without streaming?

I can't see anything different between the ITK and simpleitk implementations. Where are the big differences occurring? Is it some kind of chunk effect?

**Comment by romangrothausmann** [comment]
Seems the problem actually is that the test data is a signed distance map while in 17-297e_1_s02 the distance map is unsigned and the BinaryThresholdImageFilter uses `LowerThreshold >= x >= UpperThreshold`. I'm not sure how the `>` operator in SIKT is implemented (it is not part of https://itk.org/SimpleITKDoxygen/html/sitkImageOperators_8h_source.html) but to cover both cases one would need `LowerThreshold > x >= UpperThreshold`. I can't find a filter in ITK to acomplish that. @richardbeare  do you know one?

**Comment by romangrothausmann** [comment]
I guess the `>` operator uses the [`GreaterImageFilter`](https://itk.org/SimpleITKDoxygen/html/namespaceitk_1_1simple.html#a8f32f7f7a02b80e4c25aeb09265746ec), which seems to be a special implementation for SITK based on the `BinaryFunctorImageFilter`: https://github.com/SimpleITK/SimpleITK/blob/8c1c674daa77e4fea4a495cf90a800457c309df6/Code/BasicFilters/json/GreaterImageFilter.json

**Comment by romangrothausmann** [comment]
https://github.com/romangrothausmann/ITK-CLIs/commit/d65dd8c0f2e75a660d8a19604da29b9e89a0bd13 seems to properly mimic SITK's `>` operator.

**Comment by romangrothausmann** [comment]
> Is the difference the same with and without streaming?

Yes, tested on 17-297e_1_s02 and with 
https://github.com/romangrothausmann/ITK-CLIs/blob/d65dd8c0f2e75a660d8a19604da29b9e89a0bd13/.gitlab-ci.yml#L156-L161
result: https://gitlab.com/romangrothausmann/ITK-CLIs/-/jobs/230343272

**Comment by richardbeare** [comment]
Ah, I must have masked the distance transform. A shortcut will be to mask it externally - I probably used c3d from the itksnap tools, but you may have a bunch of arithmetic tools ready to go.

Otherwise you could feed the signed DT through a ThresholdImageFilter setting the below 0 values to zero. Can't see a nice way of doing it all in one go.

**Pull request merged**
